server:
  port: ${PORT:0}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
config:
  use-legacy-processing: true

spring:
  boot:
    admin:
      client:
        url: http://localhost:10000
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always