spring:
  application:
    name: @project.artifactId@
    version: @project.version@
  profiles:
    active: local
  config:
    use-legacy-processing: true
---
spring:
  profiles: local
server:
  port: 10000