spring:
  application:
    name: @project.artifactId@
    version: @project.version@
  profiles:
    active: local

---
spring:
  profiles: local
server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8761/eureka

---
spring:
  profiles: heroku
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false