pipeline {
    agent any
    stages {
        stage("Build"){
            steps {
                echo("Start Build")
                sh("cd admin; ./mwnw clean compile test-compile")
                echo("Finish Build")
            }
        }
        stage("Test"){
            steps {
                echo("Start Test")
                sh("cd admin; ./mwnw test")
                echo("Finish Test")
            }
        }
        stage("Deploy"){
            steps {
                echo("Deployment is finished")
            }
        }
    }

    post {
        always {
            echo "I will always say hello"
        }
        success {
            echo "Yeay, success !!"
        }
        failure {
            echo "Ooops, failure !!"
        }
        cleanup {
            echo "Don't care with success or failure"
        }
    }
}