pipeline {
    agent any
    stages {
        stage("Build"){
            steps {
                echo("Start Build")
                sh("cd admin; ./mvnw clean compile test-compile")
                echo("Finish Build")
            }
        }
        stage("Test"){
            steps {
                echo("Start Test")
                sh("cd admin; ./mvnw test")
                echo("Finish Test")
            }
        }
        stage("Deploy"){
            steps {
                echo("Deploy start")
                script {
                    for (int i = 1; i <= 5; i++) {
                        echo("Process ${i}")
                    }
                }
                echo("Deploy finish")
            }
        }
    }

    post {
        always {
            echo "I will always say hello"
        }
        success {
            echo "Yeay, success !!"
        }
        failure {
            echo "Ooops, failure !!"
        }
        cleanup {
            echo "Don't care with success or failure"
        }
    }
}