pipeline {
    agent any
    stages {
        stage("Hello"){
            steps {
                echo("Hello Pipeline")
            }
        }
    }

    post {
        always {
            echo "I will always say hello"
        }
        success {
            echo "Yeay, success !!"
        }
        failure {
            echo "Ooops, failure !!"
        }
        cleanup {
            echo "Don't care with success or failure"
        }
    }
}